"""
Assignment 2: LLM-as-Judge / LLM-as-Reward-Model
=================================================
Directly bridges GenAI and RL: using an LLM to produce scalar reward signals
that can supervise policy optimization (the RLAIF paradigm).

Topics:
  - Pairwise preference elicitation (A vs B)
  - Pointwise scoring with calibration
  - Position bias and mitigation
  - Converting LLM preferences to a reward model via Bradley-Terry
  - Measuring agreement with human preference proxies

Paper refs:
  - Constitutional AI (Bai et al. 2022)  https://arxiv.org/abs/2212.06950
  - RLAIF (Lee et al. 2023)  https://arxiv.org/abs/2309.00267
  - PandaLM (Wang et al. 2023)  https://arxiv.org/abs/2306.05087

Setup: pip install anthropic numpy scipy && export ANTHROPIC_API_KEY=...
"""

import json
import random
import numpy as np
from scipy.optimize import minimize
import anthropic

client = anthropic.Anthropic()
MODEL = "claude-haiku-4-5-20251001"

# ---------------------------------------------------------------------------
# Synthetic dataset: (prompt, response_A, response_B, ground_truth_winner)
# Simulates the kind of preference pairs used in RLHF data collection.
# ---------------------------------------------------------------------------

PREFERENCE_PAIRS = [
    {
        "prompt": "Explain the exploration-exploitation tradeoff in RL.",
        "response_a": (
            "You need to balance trying new things versus using what works. "
            "This is a key challenge in RL."
        ),
        "response_b": (
            "The exploration-exploitation tradeoff reflects the fundamental tension "
            "between gathering information about unknown rewards (exploration) and "
            "maximizing cumulative reward using current knowledge (exploitation). "
            "Formally, in a bandit setting this manifests as regret: "
            "R_T = T·μ* − Σ μ_{a_t}. UCB algorithms achieve O(√T log T) regret "
            "by maintaining optimistic reward estimates."
        ),
        "ground_truth": "B",
    },
    {
        "prompt": "What is the difference between on-policy and off-policy learning?",
        "response_a": (
            "On-policy methods learn from data generated by the current policy "
            "(e.g., SARSA, PPO). Off-policy methods can learn from data generated "
            "by any behavior policy, enabling experience replay and learning from "
            "demonstrations (e.g., Q-learning, SAC, DQN). The key challenge in "
            "off-policy learning is correcting for distributional shift via "
            "importance sampling: ρ = π(a|s)/μ(a|s)."
        ),
        "response_b": (
            "On-policy uses the current policy, off-policy uses old data. "
            "PPO is on-policy. DQN is off-policy."
        ),
        "ground_truth": "A",
    },
    {
        "prompt": "How does PPO prevent large policy updates?",
        "response_a": (
            "PPO clips the probability ratio r_t(θ) = π_θ(a|s)/π_θ_old(a|s) "
            "within [1−ε, 1+ε] and takes the minimum with the unclipped objective: "
            "L^CLIP = E[min(r_t·Â, clip(r_t, 1−ε, 1+ε)·Â)]. "
            "This creates a pessimistic lower bound that discourages moves outside "
            "the trust region without requiring second-order information."
        ),
        "response_b": (
            "PPO adds a KL divergence penalty to the loss function to prevent "
            "the new policy from deviating too much from the old policy. "
            "This keeps updates stable."
        ),
        "ground_truth": "A",  # B describes the KL-penalty variant, A is CLIP
    },
]


# ---------------------------------------------------------------------------
# Part 1: Pairwise preference elicitation
# ---------------------------------------------------------------------------

def get_pairwise_preference(prompt: str, response_a: str, response_b: str) -> str:
    """
    Ask the LLM which response is better. Return "A", "B", or "tie".

    TODO: Design a judge prompt that evaluates on:
      - Accuracy and depth
      - Use of precise technical language
      - Appropriate level of detail for an expert audience
    Parse the output and return the winner.
    """
    raise NotImplementedError


def measure_position_bias(pair: dict, n_trials: int = 5) -> dict:
    """
    Position bias: LLM judges often prefer whichever response appears first.

    TODO:
      1. Call get_pairwise_preference with (A, B) ordering n_trials times.
      2. Call with (B, A) ordering n_trials times, flipping the returned label.
      3. Compute: bias = P(prefer_first) and consistency = P(same_winner_both_orders).
      4. Return {"bias": float, "consistency": float, "winner_ab": str, "winner_ba": str}.
    """
    raise NotImplementedError


# ---------------------------------------------------------------------------
# Part 2: Pointwise scoring with calibration
# ---------------------------------------------------------------------------

def get_pointwise_score(prompt: str, response: str) -> float:
    """
    Score a single response on [1, 10]. Return the float.

    TODO: Prompt for a score with explicit rubric. Extract the number.
    Bonus: ask for a chain-of-thought before the score to improve calibration.
    """
    raise NotImplementedError


def score_all_responses() -> list[dict]:
    """
    TODO: Score response_a and response_b for every pair in PREFERENCE_PAIRS.
    Aggregate: does the higher-scored response match ground_truth?
    Report pointwise accuracy and mean score gap.
    """
    raise NotImplementedError


# ---------------------------------------------------------------------------
# Part 3: Bradley-Terry reward model from collected preferences
# ---------------------------------------------------------------------------

def bradley_terry_fit(wins: np.ndarray) -> np.ndarray:
    """
    Fit Bradley-Terry model: P(i beats j) = σ(r_i − r_j).
    `wins[i, j]` = number of times item i was preferred over item j.

    TODO: Minimize negative log-likelihood using scipy.optimize.minimize.
    Return reward scores r ∈ R^n (normalize so r.mean() == 0).

    The NLL is: -Σ_{i,j} [wins[i,j] * log σ(r_i - r_j)]
    """
    raise NotImplementedError


def build_wins_matrix(preferences: list[tuple[int, int]]) -> np.ndarray:
    """
    preferences: list of (winner_idx, loser_idx) pairs.
    Build wins[i,j] count matrix for Bradley-Terry fitting.
    """
    # TODO
    raise NotImplementedError


# ---------------------------------------------------------------------------
# Part 4: Calibration analysis
# ---------------------------------------------------------------------------

def calibration_analysis():
    """
    TODO:
      1. Collect pairwise preferences for all pairs (with both orderings).
      2. Fit Bradley-Terry model.
      3. Check: does BT ranking agree with ground_truth ranking?
      4. Print a summary: pairwise accuracy, BT scores per response.
    """
    raise NotImplementedError


if __name__ == "__main__":
    random.seed(42)

    print("=== Position Bias Analysis ===")
    for pair in PREFERENCE_PAIRS[:1]:
        result = measure_position_bias(pair, n_trials=4)
        print(json.dumps(result, indent=2))

    print("\n=== Pointwise Scoring ===")
    score_all_responses()

    print("\n=== Bradley-Terry Calibration ===")
    calibration_analysis()
